services:
  my-server:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      my-db:
        condition: service_healthy
      my-cache-server:
        condition: service_healthy
    entrypoint: ["java", "-jar", "/app.jar"]
    networks:
      - my-network

  my-db:
    image: mysql
    environment:
      MYSQL_DATABASE: sokchoys
    volumes:
      - /Users/ihuiju/sokchoys/data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 10
    networks:
      - my-network

  my-cache-server:
    image: redis
    environment:
      - TZ=Asia/Seoul
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
    networks:
      - my-network

networks:
  my-network:
